spring.application.name=events
server.port=8082
spring.kafka.bootstrap-servers=${KAFKA_BROKERS:127.0.0.1:9092}
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer