apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJibWxyWkdWMmN6cG5hSEJmYjI5TGQzQlFPV0ZKWVdoMVoxbFRTbXhOUTBrMWNtZExkazloWVhKSU5FbHdNR3AxIgoJCX0KCX0sCgkiY3JlZHNTdG9yZSI6ICJ3aW5jcmVkIgp9
type: kubernetes.io/dockerconfigjson
